name: 打包应用并上传腾讯云
on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # 安装Node10
      - name: Install Node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v2
        with:
            node-version: 16.20.2

      # 安装依赖
      - name: Install npm dependencies
        run: npm install

      # 打包
      - name: Run build task
        run: npm run build
      # 上传阿里云
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-rltgoDzvO --delete"
          # 源目录
          SOURCE: 'dist'
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/www/wwwroot'
